name: actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple JS actons
        id: greet
        uses: actions/hello-world-javascript-action@master
        # u can use versions or commit id instead of master above
        with:
          who-to-greet: Vny
      - name: log greeting time 
        run: echo "${{ steps.greet.outputs.time }}"
